-- 002.sql
-- --> CUSTOMER

CREATE TABLE CUSTOMER (
	ID INT PRIMARY KEY,
    `NAME` VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    PHONE INT NOT NULL,
    `PASSWORD` VARCHAR(50) NOT NULL
);
