-- 003.sql
-- --> DEPARTMENT, EMPLOYEE

CREATE TABLE DEPARTMENT (
	ID INT PRIMARY KEY,
    `NAME` VARCHAR(50) NOT NULL
);

CREATE TABLE EMPLOYEE (
	ID INT PRIMARY KEY,
    `NAME` VARCHAR(50) NOT NULL,
    PHONE INT NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    DEPARTMENT_ID INT,
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);