-- 004.sql
-- --> PAYMENT_METHOD, ORDER_STATUS

CREATE TABLE PAYMENT_METHOD (
	ID INT PRIMARY KEY,
    `DESC` VARCHAR(50)
);

CREATE TABLE ORDER_STATUS (
	ID INT PRIMARY KEY,
    `DESC` VARCHAR(50)
);