-- 005.sql
-- --> ORDER, BILL, ORDER_DETAIL, ORDER_STATUS_DETAIL

CREATE TABLE `ORDER` (
	ID INT PRIMARY KEY,
    DELIVERY_FEE DOUBLE NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    PAYMENT_METHOD_ID INT,
    EMPLOYEE_ID INT,
    CUSTOMER_ID INT,
    CONSTRAINT FK_ORDER_PAYMENT_METHOD FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(ID),
    CONSTRAINT FK_ORDER_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (EMPLOYEE_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE BILL (
	ID INT PRIMARY KEY,
    CREATED_AT DATETIME NOT NULL,
    TOTAL_OF_MONEY DOUBLE NOT NULL,
    ORDER_ID INT,
    CONSTRAINT FK_BILL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID)
);

CREATE TABLE ORDER_DETAIL (
	ID INT PRIMARY KEY,
    ORDER_ID INT UNIQUE,
    ITEM_DETAIL_ID INT UNIQUE,
    AMOUNT INT NOT NULL,
    CONSTRAINT FK_ORDER_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
	CONSTRAINT FK_ORDER_DETAIL_ITEM_DETAIL FOREIGN KEY (ITEM_DETAIL_ID) REFERENCES ITEM_DETAIL(ID)
);

CREATE TABLE ORDER_STATUS_DETAIL (
	ID INT PRIMARY KEY,
    ORDER_ID INT UNIQUE,
    ORDER_STATUS_ID INT UNIQUE,
    EMPLOYEE_ID INT NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    CONSTRAINT FK_ORDER_STATUS_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
	CONSTRAINT FK_ORDER_STATUS_DETAIL_ORDER_STATUS FOREIGN KEY (ORDER_STATUS_ID) REFERENCES ORDER_STATUS(ID),
    CONSTRAINT FK_ORDER_STATUS_DETAIL_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);

