-- Patches to creating tables
-- --> ORDER, BILL, ORDER_DETAIL, ORDER_STATUS_DETAIL
USE java20_shopping;

-- create table ORDER
DROP TABLE IF EXISTS `ORDER`;
CREATE TABLE `ORDER`
(
	ID INT,
    `DELIVERY_FEE` INT NOT NULL,
	`CREATE_AT` DATE NOT NULL,
    `PAYMENT_METHOD_ID` INT NOT NULL,
	`EMPLOYEE_ID` INT NOT NULL,
    `CUSTOMER_ID` INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_PAYMENT_METHOD FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(ID),
    CONSTRAINT FK_ORDER_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

-- create table BILL
DROP TABLE IF EXISTS BILL;
CREATE TABLE BILL
(
	ID INT,
    `CREATE_AT` DATE NOT NULL,
	`TOTAL_OF_MONEY` FLOAT NOT NULL,
    `ORDER_ID` INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_BILL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID)
);

-- create table BILL
DROP TABLE IF EXISTS ORDER_STATUS_DETAIL;
CREATE TABLE ORDER_STATUS_DETAIL
(
	ID INT,
    `UPDATE_AT` DATE NOT NULL,
    `ORDER_ID` INT NOT NULL,
    `ORDER_STATUS_ID` INT NOT NULL,
    `EMPLOYEE_ID` INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_STATUS_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_ORDER_STATUS_DETAIL_ORDER_STATUS FOREIGN KEY (ORDER_STATUS_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_ORDER_STATUS_DETAIL_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES `ORDER`(ID)
);