-- 007.sql
-- --> PROVIDER, TITLE, EMPLOYEE_TITLE, DELIVERY_STATUS, ORDER_DELIVERY_STATUS_DETAIL

-- create table PROVIDER
DROP TABLE IF EXISTS `PROVIDER`;
CREATE TABLE IF NOT EXISTS `PROVIDER`
(
	ID INT,
	`NAME` VARCHAR(100) NOT NULL,
    TAX_CODE VARCHAR(20) NOT NULL,
    ADDRESS TEXT NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
);

-- create table TITLE
DROP TABLE IF EXISTS `TITLE`;
CREATE TABLE IF NOT EXISTS `TITLE`
(
	ID INT,
	`NAME` VARCHAR(100) NOT NULL,
    `DESC` TEXT NOT NULL,
    STIPEND DOUBLE NOT NULL,
    PRIMARY KEY (ID)
);

-- create table EMPLOYEE_TITLE
DROP TABLE IF EXISTS `EMPLOYEE_TITLE`;
CREATE TABLE IF NOT EXISTS `EMPLOYEE_TITLE`
(
	EMPLOYEE_ID INT,
	TITLE_ID INT,
    PRIMARY KEY (EMPLOYEE_ID, TITLE_ID),
    CONSTRAINT FK_EMPLOYEE_EMPLOYEE_TITLE FOREIGN KEY (EMPLOYEE_ID) REFERENCES `EMPLOYEE`(ID),
    CONSTRAINT FK_TITLE_EMPLOYEE_TITLE FOREIGN KEY (TITLE_ID) REFERENCES `TITLE`(ID)
);

-- create table DELIVERY_STATUS
DROP TABLE IF EXISTS `DELIVERY_STATUS`;
CREATE TABLE IF NOT EXISTS `DELIVERY_STATUS`
(
	ID INT,
    `DESC` TEXT NOT NULL,
    PRIMARY KEY (ID)
);

-- create table ORDER_DELIVERY_STATUS_DETAIL
DROP TABLE IF EXISTS `ORDER_DELIVERY_STATUS_DETAIL`;
CREATE TABLE IF NOT EXISTS `ORDER_DELIVERY_STATUS_DETAIL`
(
	ORDER_ID INT NOT NULL,
    STATUS_ID INT NOT NULL,
    EMPLOYEE_ID INT NOT NULL,
    LAST_UPDATED_AT DATETIME NOT NULL DEFAULT current_timestamp(),
    PRIMARY KEY (ORDER_ID, STATUS_ID),
    CONSTRAINT FK_ORDER_ORDER_DELIVERY_STATUS_DETAIL FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_DELIVERY_STATUS_ORDER_ORDER_DELIVERY_STATUS_DETAIL FOREIGN KEY (STATUS_ID) REFERENCES `DELIVERY_STATUS`(ID),
    CONSTRAINT FK_EMPLOYEE_ORDER_DELIVERY_STATUS_DETAIL FOREIGN KEY (EMPLOYEE_ID) REFERENCES `EMPLOYEE`(ID)
);