-- Patches to create tables
-- CUSTOMER

-- CREATE TABLE CUSTOMER
CREATE TABLE CUSTOMER
(
	`ID` 			INT,
    `NAME` 			VARCHAR(100) NOT NULL,
    `EMAIL` 		VARCHAR(100) NOT NULL,
    `ADDRESS` 		VARCHAR(100) NOT NULL,
    `PHONE` 		VARCHAR(20) NOT NULL,
    `PASSWORD` 		VARCHAR(100) NOT NULL,
    CONSTRAINT 		PRIMARY KEY(ID)
);