-- Patches to creating tables
-- --> PAYMENT_METHOD, ORDER_STATUS
USE java20_shopping;

-- create table PAYMENT_METHOD
DROP TABLE IF EXISTS PAYMENT_METHOD;
CREATE TABLE PAYMENT_METHOD
(
	ID INT,
    `DESC` VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

-- create table ORDER_STATUS
DROP TABLE IF EXISTS ORDER_STATUS;
CREATE TABLE ORDER_STATUS
(
	ID INT,
    `DESC` VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);