CREATE TABLE IF NOT EXISTS PROVIDER
(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL,
    TAX_CODE VARCHAR(20) NOT NULL,
    ADDRESS TEXT NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE item
	ADD COLUMN IMAGE_01 VARCHAR(100) AFTER MATERIAL;
ALTER TABLE item
	ADD COLUMN IMAGE_02 VARCHAR(100) AFTER IMAGE_01;
ALTER TABLE item
	ADD COLUMN LAST_UPDATE_AT DATETIME AFTER IMAGE_02;
ALTER TABLE item
	ADD COLUMN PROVIDER_ID INT;
ALTER TABLE item
ADD CONSTRAINT FK_ITEM_PROVIDER FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDER(ID);

SELECT it.ID, it.NAME, od.CREATED_AT
FROM item it
JOIN item_detail id
ON it.ID = id.ITEM_ID
JOIN order_detail odd
ON id.ID = odd.ITEM_DETAIL_ID
JOIN `order` od
ON od.ID = odd.ORDER_ID
WHERE cast(od.CREATED_AT as DATE) = '2023-02-15';

SELECT it.ID, it.NAME, SUM(odd.AMOUNT) SALES_AMOUNT
  FROM item it
JOIN item_detail id
ON it.ID = id.ITEM_ID
JOIN order_detail odd
ON id.ID = odd.ITEM_DETAIL_ID
JOIN `order` od
ON od.ID = odd.ORDER_ID
WHERE year(od.CREATED_AT) = '2023'
GROUP BY it.ID, it.NAME
ORDER BY SALES_AMOUNT desc, it.ID desc
LIMIT 3;

