-- Patches to creating tables:
-- DEPARTMENT, EMPLOYEE

USE java20_shopping;

-- create table DEPARTMENT
DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE DEPARTMENT
(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

-- create table EMPLOYEE
DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE
(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL,
    `PHONE` VARCHAR(10) NOT NULL,
    `ADDRESS` VARCHAR(100) NOT NULL,
    `DEPARTMENT_ID` INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_EMPLOYEE_EMPLOYEE FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);