drop database QUANLYCUAHANG;
CREATE DATABASE QUANLYCUAHANG CHAR SET utf8mb4;

DROP TABLE IF EXISTS KHACHHANG;
CREATE TABLE IF NOT EXISTS KHACHHANG
(
	MAKH VARCHAR(10),
    TENKH VARCHAR(100) NOT NULL,
    DAICHI VARCHAR(100),
    SODT VARCHAR(20),
    MASOTHUE VARCHAR(20) UNIQUE,
    PRIMARY KEY (MAKH)
);

DROP TABLE IF EXISTS MUCTIENGIO;
CREATE TABLE IF NOT EXISTS MUCTIENGIO
(
	MATIENGIO VARCHAR(10),
    DONGIA DECIMAL(10, 2) NOT NULL,
    MOTA VARCHAR(100),
    PRIMARY KEY (MATIENGIO)
);

DROP TABLE IF EXISTS PHONG;
CREATE TABLE IF NOT EXISTS PHONG
(
	MAPHONG VARCHAR(10),
    SOKHACHTOIDA INT NOT NULL,
    TRANGTHAI VARCHAR(100),
    MOTA VARCHAR(100),
     PRIMARY KEY (MAPHONG)
);

DROP TABLE IF EXISTS DICHVU;
CREATE TABLE IF NOT EXISTS DICHVU
(
	MADV VARCHAR(10),
    TENDICHVU VARCHAR(100) NOT NULL,
    DONVITINH VARCHAR(20),
    DONGIA DECIMAL(10, 2),
     PRIMARY KEY (MADV)
);

DROP TABLE IF EXISTS HOADON;
CREATE TABLE IF NOT EXISTS HOADON
(
	MAHD VARCHAR(10),
    MAKH VARCHAR(10) NOT NULL,
    MAPHONG VARCHAR(10) NOT NULL,
    MATIENGIO VARCHAR(10) NOT NULL,
    THOIGIANBATDAUSD  DATETIME NOT NULL DEFAULT current_timestamp(),
    THOIGIANKETTHUCSD  DATETIME NOT NULL DEFAULT current_timestamp(),
    TRANGTHAIHD VARCHAR(100),
     PRIMARY KEY (MAHD),
     CONSTRAINT FK_HOADON_KHACHHANG
		FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
        CONSTRAINT FK_HOADON_PHONG
		FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG),
        CONSTRAINT FK_HOADON_MUCTIENGIO
		FOREIGN KEY (MATIENGIO) REFERENCES MUCTIENGIO(MATIENGIO)
);

DROP TABLE IF EXISTS CHITIET_SUDUNGDV;
CREATE TABLE IF NOT EXISTS CHITIET_SUDUNGDV
(
	MAHD VARCHAR(10),
    MADV VARCHAR(10) NOT NULL,
    SOLUONG INT NOT NULL,
     PRIMARY KEY (MAHD,MADV),
     CONSTRAINT FK_CHITIET_SUDUNGDV_HOADON
		FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
        CONSTRAINT FK_CHITIET_SUDUNGDV_DICHVU
		FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)
);


------------------ INSERT ---------------

SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO KHACHHANG (MAKH, TENKH, DAICHI, SODT, MASOTHUE) VALUES
('KH001', 'Tran Van Nam', 'Hai Chau', '0905123456', '12345678'),
('KH002', 'Nguyen Mai Anh', 'Lien Chieu', '0905123456', '12345679');

INSERT INTO MUCTIENGIO (MATIENGIO, DONGIA, MOTA) VALUES
('MT01', 60000.00, 'Ap dung tu 6 gio den 17 gio'),
('MT02', 80000.00, 'Ap dung sau 17 gio den 22 gio');

INSERT INTO PHONG (MAPHONG, SOKHACHTOIDA, TRANGTHAI, MOTA) VALUES
('VIP01', 5, 'Duoc su dung', 'phong vip'),
('P02', 10, 'Duoc su dung', 'phong binh thuong');

INSERT INTO DICHVU (MADV, TENDICHVU, DONVITINH, DONGIA) VALUES
('DV01', 'Hat Dua', 'Bao', 5000.00),
('DV02', 'Trai cay', 'Dia', 30000.00);

INSERT INTO HOADON (MAHD, MAKH, MAPHONG, MATIENGIO, THOIGIANBATDAUSD, THOIGIANKETTHUCSD, TRANGTHAIHD) VALUES
('HD001', 'KH002','VIP01', 'MT01', str_to_date('7/7/2023 8:05', '%d/%m/%Y %H:%i'), str_to_date('7/7/2023 12:05', '%d/%m/%Y %H:%i'), 'Da thanh toan'),
('HD002', 'KH002','P02', 'MT02', str_to_date('7/7/2023 13:10', '%d/%m/%Y %H:%i'), str_to_date('7/7/2023 17:10', '%d/%m/%Y %H:%i'), 'Da thanh toan');

INSERT INTO CHITIET_SUDUNGDV (MAHD, MADV, SOLUONG) VALUES
('HD001', 'DV01', 5),
('HD002', 'DV01', 8);


										------------------ --------------

/* --- Liệt kê các phòng karaoke được sử dụng nhiều nhất từ 02.2014 đến 02.2015 */

SELECT p.MAPHONG, 
	   p.MOTA, 
       COUNT(h.MAHD) AS SO_LUONG_SU_DUNG
  FROM HOADON h
  JOIN PHONG p ON h.MAPHONG = p.MAPHONG
  WHERE h.THOIGIANBATDAUSD >= '2014-02-01' AND 
		h.THOIGIANBATDAUSD < '2015-03-01'
  GROUP BY p.MAPHONG, p.MOTA
  ORDER BY SO_LUONG_SU_DUNG DESC;
  
  /* Liệt kê 2 dịch vụ được sử dụng nhiều nhất trong mỗi tháng từ 01.2014 đến 12.2014 */
  
SELECT MONTH(h.THOIGIANBATDAUSD) AS THANG,
       dv.MADV, 
       dv.TENDICHVU, 
       SUM(cs.SOLUONG) AS TONG_SO_LUONG
 FROM CHITIET_SUDUNGDV cs
 JOIN HOADON h 
	ON cs.MAHD = h.MAHD
 JOIN DICHVU dv 
	ON cs.MADV = dv.MADV
 WHERE h.THOIGIANBATDAUSD >= '2014-01-01' AND 
       h.THOIGIANBATDAUSD < '2015-01-01'
GROUP BY MONTH(h.THOIGIANBATDAUSD), dv.MADV, dv.TENDICHVU
ORDER BY THANG, 
         TONG_SO_LUONG DESC;
    

/*Liệt kê thông tin của các phòng karaoke có mã phòng bắt đầu bằng cụm từ "VIP"*/

SELECT *
  FROM PHONG
  WHERE MAPHONG LIKE 'VIP%';






