USE JAVA20_FOOTBALL;

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER
(
	ID INT NOT NULL,
    `NAME` VARCHAR(50) NOT NULL,
    `PASSWORD` VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    PHONE INT NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS FIELD;
CREATE TABLE FIELD
(
	ID INT NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    `STATUS` VARCHAR(250) NOT NULL,
    SLOT INT NOT NULL,
    PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS BOOKING;
CREATE TABLE BOOKING
(
	ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    BOOKING_DATE DATETIME NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT PK_BOOKING_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

DROP TABLE IF EXISTS TEAM;
CREATE TABLE TEAM
(
	ID INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    AMOUNT INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_TEAM_CUSTOMER FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

DROP TABLE IF EXISTS `MATCH`;
CREATE TABLE `MATCH`
(
	ID INT NOT NULL,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    FIELD_ID INT NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_MATCH_FIELD FOREIGN KEY(FIELD_ID) REFERENCES FIELD(ID)
);

DROP TABLE IF EXISTS REVIEW;
CREATE TABLE REVIEW
(
	ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    RATING VARCHAR(250) NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_REVIEW_CUSTOMER FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

DROP TABLE IF EXISTS PAYMENT;
CREATE TABLE PAYMENT
(
	ID INT NOT NULL,
    BOOKING_ID INT NOT NULL,
    PRICE INT NOT NULL,
    PAYMENT_DATE DATETIME NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_PAYMENT_BOOKING FOREIGN KEY(BOOKING_ID) REFERENCES BOOKING(ID)
);

DROP TABLE IF EXISTS BOOKING_DETAIL;
CREATE TABLE BOOKING_DETAIL
(
	ID INT NOT NULL,
    BOOKING_ID INT NOT NULL,
    FIELD_ID INT NOT NULL,
    AMOUNT INT NOT NULL,
    `DESC` VARCHAR(250) NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT UNQ_BOOKING_FIELD UNIQUE (BOOKING_ID,FIELD_ID),
    CONSTRAINT FK_BOOKING_DETAIL_BOOKING FOREIGN KEY(BOOKING_ID) REFERENCES BOOKING(ID),
    CONSTRAINT FK_BOOKING_DETAIL_FIELD FOREIGN KEY(FIELD_ID) REFERENCES FIELD(ID)
);


DROP TABLE IF EXISTS MATCH_DETAIL;
CREATE TABLE MATCH_DETAIL
(
	ID INT NOT NULL,
    TEAM_ID INT NOT NULL,
    MATCH_ID INT NOT NULL,
    RESULT VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT UNQ_TEAM_MATCH UNIQUE (TEAM_ID,MATCH_ID),
    CONSTRAINT FK_MATCH_DETAIL_TEAM FOREIGN KEY(TEAM_ID) REFERENCES TEAM(ID),
    CONSTRAINT FK_MATCH_DETAIL_MATCH FOREIGN KEY(MATCH_ID) REFERENCES `MATCH`(ID)
);