-- Patches to creating tables
-- CUSTOMER

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE IF NOT EXISTS CUSTOMER
(
	ID INT,
    `NAME`	VARCHAR(100) NOT NULL,
    EMAIL	VARCHAR(100) NOT NULL,
    ADDRESS	VARCHAR(100) NOT NULL,
    PHONE	VARCHAR(50) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

-- rename column ADDRESS VARCHAR to ADDRESS TEXT
ALTER TABLE CUSTOMER CHANGE ADDRESS ADDRESS TEXT NOT NULL;