-- Patches to creating tables
-- PAYMENT_METHOD, ORDER_STATUS

DROP TABLE IF EXISTS PAYMENT_METHOD;
CREATE TABLE IF NOT EXISTS PAYMENT_METHOD
(
	ID INT,
    `DESC` TEXT NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ORDER_STATUS;
CREATE TABLE IF NOT EXISTS ORDER_STATUS
(
	ID INT,
    `DESC` TEXT NOT NULL,
    PRIMARY KEY (ID)
);