-- Patches to creating tables
-- ORDER, BILL, ORDER_DETAIL, ORDER_STATUS_DETAIL

SELECT current_timestamp();
DROP TABLE IF EXISTS `ORDER`;
CREATE TABLE IF NOT EXISTS `ORDER`
(
	ID INT,
    DELIVERY_FEE INT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    PAYMENT_METHOD_ID INT NOT NULL,
    EMPLOYEE_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    CONSTRAINT FK_ORDER_PAYMENT_METHOD FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(ID),
    CONSTRAINT FK_ORDER_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)    
);
ALTER TABLE `ORDER` CHANGE DELIVERY_FEE DELIVERY_FEE FLOAT;
ALTER TABLE `ORDER` CHANGE CREATED_AT CREATED_AT DATETIME NOT NULL DEFAULT current_timestamp();
ALTER TABLE `ORDER` ADD COLUMN DELIVERY_ADDRESS TEXT NOT NULL AFTER ID;

DROP TABLE IF EXISTS BILL;
CREATE TABLE IF NOT EXISTS BILL
(
	ID INT,
    CREATED_AT DATETIME NOT NULL,
    TOTAL_OF_MONEY INT NOT NULL,
    ORDER_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_BILL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT UNQ_BILL UNIQUE (ORDER_ID)
);
ALTER TABLE BILL CHANGE CREATED_AT CREATED_AT DATETIME NOT NULL DEFAULT current_timestamp();
ALTER TABLE BILL CHANGE TOTAL_OF_MONEY TOTAL_OF_MONEY FLOAT NOT NULL;

DROP TABLE IF EXISTS ORDER_DETAIL;
CREATE TABLE IF NOT EXISTS ORDER_DETAIL
(
	ID INT,
    ORDER_ID INT NOT NULL,
    ITEM_DETAIL_ID INT NOT NULL,
    AMOUNT INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_ORDER_DETAIL_ITEM_DETAIL FOREIGN KEY (ITEM_DETAIL_ID) REFERENCES ITEM_DETAIL(ID),
    CONSTRAINT UNQ_ORDER_ITEM_DETAIL UNIQUE (ORDER_ID, ITEM_DETAIL_ID)
);

DROP TABLE IF EXISTS ORDER_STATUS_DETAIL;
CREATE TABLE IF NOT EXISTS ORDER_STATUS_DETAIL
(
	ID INT,
    ORDER_ID INT NOT NULL,
    ORDER_STATUS_ID INT NOT NULL,
    EMPLOYEE_ID INT NOT NULL,
    UPDATE_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_STATUS_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_ORDER_STATUS_DETAIL_ORDER_STATUS FOREIGN KEY (ORDER_STATUS_ID) REFERENCES ORDER_STATUS(ID),
    CONSTRAINT FK_ORDER_STATUS_DETAIL_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT UNQ_ORDER_ORDER_STATUS UNIQUE (ORDER_ID, ORDER_STATUS_ID)
);
ALTER TABLE ORDER_STATUS_DETAIL CHANGE UPDATE_AT UPDATE_AT DATETIME NOT NULL DEFAULT current_timestamp();

-- In each table
-- create index, partition (fast filtering)
-- create view
-- create trigger (aop [aspect object progaraming])