CREATE DATABASE KARAOKE_SERVICE;
USE KARAOKE_SERVICE;

-- Câu 1 
CREATE TABLE KHACHHANG (
	MaKH VARCHAR(10) PRIMARY KEY,
    TenKH VARCHAR(50), -- nên thêm ràng buộc not null em nha
    DiaChi VARCHAR(50),
    SoDT VARCHAR(11),
    MaSoThue VARCHAR(11)
);

CREATE TABLE MUCTIENGIO (
	MaTienGio VARCHAR(10) PRIMARY KEY,
    DonGia INT,
    MoTa VARCHAR(100)
);

CREATE TABLE PHONG (
	MaPhong VARCHAR(10) PRIMARY KEY,
    SoKhachToiDa INT,
    TrangThai VARCHAR(20),
    MoTa VARCHAR(100)
);

CREATE TABLE DICHVU (
	MaDV VARCHAR(10) PRIMARY KEY,
    TenDV VARCHAR(20),
    DonViTinh VARCHAR(10),
    DonGia INT
);

CREATE TABLE HOADON (
	MaHD VARCHAR(10) PRIMARY KEY,
	MaKH VARCHAR(10) NOT NULL,
    MaPhong VARCHAR(10) NOT NULL,
    MaTienGio VARCHAR(10) NOT NULL,
    ThoiGianBatDauSD DATETIME,
    ThoiGianKetThucSD DATETIME,
    TrangThaiHD VARCHAR(50),
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong),
    FOREIGN KEY (MaTienGio) REFERENCES MUCTIENGIO(MaTienGio)
    -- Thếu UNIQUE CONSTRAINT cho (MaKH, MaPhong, MaTienGio)
);

CREATE TABLE CHITIET_SUDUNGDV (
	MaHD VARCHAR(10) NOT NULL,
    MaDV VARCHAR(10) NOT NULL,
    SoLuong INT,
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV),
    PRIMARY KEY (MaHD, MaDV)
);