CREATE TABLE KHACHHANG (
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH VARCHAR(100),
    DiaChi VARCHAR(255),
    SoDT VARCHAR(15),
    MaSoThue VARCHAR(20)
    -- hầu hết bị thiếu ràng buộc not null e nha
);

CREATE TABLE MUCTIENGIO (
    MaTienGio VARCHAR(10) PRIMARY KEY,
    DonGia DECIMAL(10, 2),
    MoTa TEXT
);

CREATE TABLE PHONG (
    MaPhong VARCHAR(10) PRIMARY KEY,
    SoKhachToiDa INT,
    TrangThai BOOLEAN,
    MoTa TEXT
);

CREATE TABLE DICHVU (
    MaDV VARCHAR(10) PRIMARY KEY,
    TenDV VARCHAR(100),
    DonViTinh VARCHAR(50),
    DonGia DECIMAL(10, 2)
);

CREATE TABLE HOADON (
    MaHD VARCHAR(10) PRIMARY KEY,
    MaKH VARCHAR(10),
    MaPhong VARCHAR(10),
    MaTienGio VARCHAR(10),
    ThoiGianBatDauSD DATETIME,
    ThoiGianKetThucSD DATETIME,
    TrangThaiHD BOOLEAN,
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong),
    FOREIGN KEY (MaTienGio) REFERENCES MUCTIENGIO(MaTienGio)
    -- Thếu UNIQUE CONSTRAINT cho (MaKH, MaPhong, MaTienGio)
);

CREATE TABLE CHITIET_SUDUNGDV (
    MaHD VARCHAR(10),
    MaDV VARCHAR(10),
    SoLuong INT,
    PRIMARY KEY (MaHD, MaDV),
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)
);