CREATE DATABASE java20_soccer CHAR SET utf8mb4;
USE java20_soccer;

-- TYPE_OF_SOCCER_FIELD, SOCCER_FIELD, STATUS_OF_SOCCER_FIELD,STATUS_OF_SOCCER_FIELD_DETAIL
CREATE TABLE TYPE_OF_SOCCER_FIELD
(
	ID INT NOT NULL,
    `DESC` VARCHAR(100),
    PRIMARY KEY(ID)
);
CREATE TABLE SOCCER_FIELD
(
	ID INT NOT NULL,
    `NAME` VARCHAR(100),
    ADDRESS VARCHAR(100),
    TYPE_OF_SOCCER_FIELD_ID INT NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_SOCCER_FIELD_TYPE_OF_SOCCER_FIELD FOREIGN KEY (TYPE_OF_SOCCER_FIELD_ID) REFERENCES TYPE_OF_SOCCER_FIELD(ID)
);

CREATE TABLE STATUS_OF_SOCCER_FIELD
(
	ID INT NOT NULL,
    `DESC` VARCHAR(100),
    PRIMARY KEY(ID)
);

CREATE TABLE STATUS_OF_SOCCER_FIELD_DETAIL
(
	ID INT NOT NULL,
    STATUS_OF_SOCCER_FIELD_ID INT,
    SOCCER_FIELD_ID INT,
	PRIMARY KEY(ID),
    CONSTRAINT FK_STATUS_OF_SOCCER_FIELD_DETAIL_STATUS_OF_SOCCER_FIELD FOREIGN KEY (STATUS_OF_SOCCER_FIELD_ID) REFERENCES STATUS_OF_SOCCER_FIELD(ID),
     CONSTRAINT FK_STATUS_OF_SOCCER_FIELD_DETAIL_SOCCER_FIELD FOREIGN KEY (SOCCER_FIELD_ID) REFERENCES SOCCER_FIELD(ID)
);




