-- STATUS_TEAM_LIST, TEAM_LIST, RENTER
USE java20_soccer;
CREATE TABLE STATUS_TEAM_LIST
(
	ID INT NOT NULL,
    `DESC` VARCHAR(100),
    PRIMARY KEY(ID)
);

CREATE TABLE TEAM_LIST
(
	ID INT NOT NULL,
    `NAME` VARCHAR(100),
    STATUS_TEAM_LIST_ID INT,
	PRIMARY KEY(ID),
	CONSTRAINT FK_TEAM_LIST_STATUS_TEAM_LIST FOREIGN KEY (STATUS_TEAM_LIST_ID) REFERENCES STATUS_TEAM_LIST(ID)
);

CREATE TABLE RENDER
(
	ID INT NOT NULL,
    `NAME` VARCHAR(100),
    PHONE VARCHAR(10),
    TEAM_LIST_ID INT,
    PRIMARY KEY(ID),
    CONSTRAINT FK_RENDER_TEAM_LIST FOREIGN KEY (TEAM_LIST_ID) REFERENCES TEAM_LIST(ID)
);