-- PAYMENT_METHOD,SERVICE, ORDER, SERVICE_DETAIL,BILL
USE java20_soccer;
CREATE TABLE PAYMENT_METHOD
(
	ID INT NOT NULL,
    `NAME` VARCHAR(100),
    PRIMARY KEY(ID)
);

CREATE TABLE SERVICE
(
	ID INT NOT NULL,
    SERVICE_NAME VARCHAR(100),
	SERVICE_CHARGE DECIMAL(10,2),
	PRIMARY KEY(ID)  
);

CREATE TABLE `ORDER`
(
	ID INT NOT NULL, 
    CREATE_AT DATE,
    `TIME` TIME,
    DURATION TIME,
    RENTER_ID INT,
	PAYMENT_METHOD_ID INT,
	FIELD_OWNER_ID INT,
    PRIMARY KEY(ID) ,
    CONSTRAINT FK_ORDER_RENTER FOREIGN KEY (RENTER_ID) REFERENCES RENTER(ID),
    CONSTRAINT FK_ORDER_PAYMENT_METHOD FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(ID),
    CONSTRAINT FK_ORDER_FIELD_OWNER FOREIGN KEY (FIELD_OWNER_ID) REFERENCES FIELD_OWNER(ID) 
);

CREATE TABLE SERVICE_DETAIL
(
	ID INT NOT NULL,
	SERVICE_ID INT,
	ORDER_ID INT,
	PRIMARY KEY(ID) ,
    CONSTRAINT FK_SERVICE_DETAIL_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(ID),
     CONSTRAINT FK_SERVICE_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID)

);

CREATE TABLE BILL
(
	ID INT NOT NULL,
	ORDER_ID INT,
	CREATE_AT DATE,
	TOTAL_OF_MONEY DECIMAL(10,2),
	PRIMARY KEY(ID) ,
	CONSTRAINT FK_BILL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID)
);