001.sql
-- -->ITEM_GROUP, ITEM, SIZE, ITEM_DETAIL

002.sql
-- -->CUSTOMER

003.sql
-- -->DEPARMENT, EMPLOYEE

004.sql
-- -->	PAYMENT_METHOD, ORDER_STATUS

005.sql
-- -->ORDER, BILL, ORDER_DETAIL, ORDER_STATUS_DETAIL