-- -->CUSTOMER
CREATE TABLE CUSTOMER
(
	ID INT,
    `NAME`VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100),
    PHONE VARCHAR(10),
    `PASSWORD` VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID)
);