-- -->DEPARMENT, EMPLOYEE
CREATE TABLE DEPARTMENT
(	
	ID INT NOT NULL,
    `NAME` VARCHAR(100),
    PRIMARY KEY(ID) 
);

CREATE TABLE EMPLOYEE
(
	ID INT,
    DEPARTMENT_ID  INT NOT NULL,
    `NAME` VARCHAR(100),
    PHONE VARCHAR(10),
    ADDRESS VARCHAR(100),
    PRIMARY KEY(ID),
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
	
);