-- -->ORDER, BILL, ORDER_DETAIL, ORDER_STATUS_DETAIL
CREATE TABLE `ORDER`
(
	ID INT NOT NULL,
    PAYMENT_METHOD_ID INT,
    EMPLOYEE_ID INT,
    CUSTOMER_ID INT,
    DELIVERY_FEE DECIMAL(10,2),
    CREATE_AT DATE,
    PRIMARY KEY(ID),
    CONSTRAINT FK_ORDER_PAYMENT_METHOD FOREIGN KEY(PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(ID),
    CONSTRAINT FK_ORDER_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE BILL
(
	ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    CREATE_AT DATE,
    TOTAL_OF_MONEY DECIMAL(10,2),
    PRIMARY KEY(ID),
    CONSTRAINT FK_BILL_ORDER FOREIGN KEY(ORDER_ID) REFERENCES `ORDER`(ID)
);

CREATE TABLE ORDER_DETAIL
(
	ID INT NOT NULL,
    ORDER_ID INT,
    ITEM_DETAIL_ID INT,
    AMOUNT INT,
    PRIMARY KEY(ID),
    CONSTRAINT FK_ORDER_DETAIL_ORDER FOREIGN KEY(ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_ORDER_DETAIL_ITEM_DETAIL FOREIGN KEY(ITEM_DETAIL_ID) REFERENCES ITEM_DETAIL(ID)
);

CREATE TABLE ORDER_STATUS_DETAIL
(
	ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    ORDER_STATUS_ID INT NOT NULL,
    EMPLOYEE_ID INT NOT NULL,
    UPDATE_AT DATETIME,
    PRIMARY KEY(ID),
    CONSTRAINT FK_ORDER_STATUS_DETAIL_ORDER FOREIGN KEY(ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_ORDER_STATUS_DETAIL_ORDER_STATUS FOREIGN KEY(ORDER_STATUS_ID) REFERENCES ORDER_STATUS(ID),
    CONSTRAINT FK_ORDER_STATUS_DETAIL_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID) 
);

