USE java20_shopping;
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER
(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL,
    `EMAIL` VARCHAR(100) NOT NULL,
    `ADDRESS` VARCHAR(100) NOT NULL,
    `PHONE` VARCHAR(11) NOT NULL,
    `PASSWORD` VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID)
);

