USE java20_shopping;
DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT
(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE EMPLOYEE
(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL,
	`PHONE` VARCHAR(100) NOT NULL,
    `ADDRESS` VARCHAR(100) NOT NULL,
	`DEPARTMENT_ID` INT,
    PRIMARY KEY(ID),
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);